/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [
    function ({ addBase }) {
      addBase({
        ":root": {
          "--background": "0 0% 100%",
          "--foreground": "240 6% 10%",
          "--card": "0 0% 100%",
          "--card-foreground": "240 6% 4%",
          "--popover": "0 0% 100%",
          "--popover-foreground": "240 100% 11%",
          "--primary": "240 100% 11%",
          "--primary-foreground": "0 0% 100%",
          "--secondary": "240 10% 96.1%",
          "--secondary-foreground": "240 100% 11%",
          "--muted": "240 10% 96.1%",
          "--muted-foreground": "240 5% 47%",
          "--accent": "240 10% 96.1%",
          "--accent-foreground": "240 100% 11%",
          "--destructive": "0 84.2% 60.2%",
          "--destructive-foreground": "0 0% 98%",
          "--border": "240 10% 89.8%",
          "--input": "240 10% 89.8%",
          "--ring": "240 6% 10%",
          "--radius": "0.5rem",
          "--sidebar-background": "0 0% 98%",
          "--sidebar-foreground": "240 6% 10%",
          "--sidebar-accent": "240 100% 16%",
          "--sidebar-accent-foreground": "0 0% 100%",
          "--sidebar-border": "240 10% 89.8%",
          "--sidebar-ring": "240 5% 65%",
        },
        ".dark": {
          "--background": "240 30% 11%",
          "--foreground": "240 10% 98%",
          "--card": "240 30% 11%",
          "--card-foreground": "240 10% 98%",
          "--popover": "240 30% 11%",
          "--popover-foreground": "240 10% 98%",
          "--primary": "240 10% 98%",
          "--primary-foreground": "240 30% 11%",
          "--secondary": "240 30% 14.9%",
          "--secondary-foreground": "240 10% 98%",
          "--muted": "240 30% 14.9%",
          "--muted-foreground": "240 20% 63.9%",
          "--accent": "240 30% 14.9%",
          "--accent-foreground": "240 10% 98%",
          "--destructive": "0 62.8% 30.6%",
          "--destructive-foreground": "240 10% 98%",
          "--border": "240 25% 25%",
          "--input": "240 25% 25%",
          "--ring": "240 10% 83.1%",
          "--radius": "0.5rem",
          "--sidebar-background": "240 38% 10%",
          "--sidebar-foreground": "0 0% 100%",
          "--sidebar-accent": "240 100% 16%",
          "--sidebar-accent-foreground": "0 0% 100%",
          "--sidebar-border": "240 20% 38%",
        },
      });
    },
  ],
};
